# Generated by Django 4.0.1 on 2022-03-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCandiModel',
            fields=[
                ('candi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter Your Name', max_length=200)),
                ('partyname', models.CharField(help_text='Enter Party Name', max_length=200)),
                ('fathername', models.TextField(help_text='Enter Father Name', max_length=200)),
                ('phone', models.BigIntegerField(help_text='Enter Phone Number')),
                ('gmail', models.EmailField(help_text='Enter Gmail Here', max_length=254)),
                ('caste', models.CharField(help_text='Enter Caste Here', max_length=100)),
                ('quali', models.CharField(help_text='Enter Educational Qualification', max_length=200, null=True)),
                ('aadhar', models.ImageField(help_text='Upload Aadhar Image', upload_to='images/')),
                ('castecertificate', models.ImageField(help_text='Upload caste Image', upload_to='images/')),
                ('passphoto', models.ImageField(help_text='Upload  passphoto Image', upload_to='images/')),
                ('password', models.CharField(help_text='Enter Password', max_length=200)),
            ],
            options={
                'db_table': 'add candidate',
            },
        ),
        migrations.CreateModel(
            name='AddElection',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='date', help_text='Enter Date and Time', max_length=200)),
                ('election_type', models.TextField(default='election type', help_text='Enter Election Type', max_length=200)),
                ('area', models.CharField(help_text='Enter area', max_length=200)),
            ],
            options={
                'db_table': 'election_details',
            },
        ),
        migrations.CreateModel(
            name='AddPartyModel',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('partyname', models.CharField(help_text='Enter Party Name', max_length=200)),
                ('partyhead', models.TextField(help_text='Enter party Head Name', max_length=200)),
                ('position', models.CharField(default='position', help_text='Enter Position party', max_length=200)),
                ('partylogo', models.ImageField(help_text='Upload Party Logo Here', null=True, upload_to='images/')),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'party_details',
            },
        ),
        migrations.CreateModel(
            name='CandidateElectionModel',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('election', models.CharField(help_text='Enter Election', max_length=200)),
                ('party', models.CharField(help_text='Enter party Here', max_length=200)),
                ('candidate', models.CharField(help_text='Enter Candidate', max_length=200)),
            ],
            options={
                'db_table': 'candidate_in_election',
            },
        ),
    ]
