# Generated by Django 4.0.1 on 2022-03-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpartymodel',
            name='partylogo',
            field=models.ImageField(default='partylogo', help_text='Upload Party Logo Here', upload_to='images/'),
        ),
    ]
