# Generated by Django 4.0.1 on 2022-03-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_addpartymodel_partylogo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addcandimodel',
            table='candidate_details',
        ),
    ]
