# Generated by Django 4.0.1 on 2022-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregistermodel',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
