# Generated by Django 4.0.1 on 2022-03-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapp', '0002_voterregistermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregistermodel',
            name='voter_type',
            field=models.CharField(default='voter-type', max_length=100, null=True),
        ),
    ]
