# Generated by Django 4.0.1 on 2022-03-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voterapp', '0003_voterregistermodel_voter_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voterregistermodel',
            table='voter_details',
        ),
    ]
