# Generated by Django 4.0.1 on 2022-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterapp', '0004_alter_voterregistermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField()),
                ('election', models.CharField(max_length=50)),
                ('partyname', models.CharField(max_length=100)),
                ('candidate', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voting_details',
            },
        ),
    ]
